// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/69f5180fff633c6919d73199
###
// PRODUCTION
###
GET https://cse341w01-3k2g.onrender.com/contacts
###
GET https://cse341w01-3k2g.onrender.com/contacts/69f5180fff633c6919d73199
###
GET https://cse341w01-3k2g.onrender.com/chloe
###